[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "MotoSuiveur"
authors = [{name = "Peter Pachov", email = "peter.pachov@siguren.com"}]
dynamic = ["version", "description"]
